language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

services:
  - mongodb

# command to install dependencies
install: "pip install -r requirements/development.txt"

# command to run tests
script:
  - coverage run -m nose
  - flake8

# coverage!
after_success:
  coveralls

deploy:
  provider: heroku
  api_key:
    secure: O8VdWaVStqG4OjKuGBJCW1Lsj5NhYs5kXSxGrJsNouSsmCbKOfNLExceLMofPvoawv/exfeigmAlbj+bqK4DpLeqspxsd7lJ4AGomIx/nFv2q2BBMk4tyaINwPWyJpzVfHvs3T49BvChgWhLrwRUfn/1IONp6huycpgcPhOnFwA=
  app: heartbotapp
  on:
    repo: jessamynsmith/heartbot
